[project]
name = "owu-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain-text-splitters>=1.1.2",
    "llama-cloud>=2.13.0",
    "nest-asyncio>=1.6.0",
    "openai>=2.49.0",
    "python-dotenv>=1.2.2",
    "qdrant-client>=1.18.0",
]
